export const navigation = [
    {
        id: 20,
        title: 'Baza wiedzy',
        menuAttached: false,
        order: 1,
        path: '/baza-wiedzy',
        type: 'WRAPPER',
        uiRouterKey: 'baza-wiedzy',
        slug: 'baza-wiedzy-1',
        external: false,
        items: [
            {
                id: 21,
                title: 'WI-SA',
                menuAttached: false,
                order: 1,
                path: '/baza-wiedzy/wi-sa',
                type: 'WRAPPER',
                uiRouterKey: 'wi-sa',
                slug: 'baza-wiedzy-wi-sa',
                external: false,
                items: [
                    {
                        id: 26,
                        title: 'Hasła SZOI/SNRL',
                        menuAttached: false,
                        order: 1,
                        path: '/baza-wiedzy/wi-sa/hasla-szoi-snrl',
                        type: 'INTERNAL',
                        uiRouterKey: 'hasla-szoi-snrl',
                        slug: 'baza-wiedzy-wi-sa-hasla-szoi-snrl',
                        external: false,
                        related: {
                            id: 2,
                            title: 'Hasła SZOI/SNRL',
                            content:
                                '<p>Wszystkie wnioski o nowe hasło procedujemy w EZD. Każdy wniosek o nowe hasło rejestrujemy pod JRWA <span style="color:hsl(120,75%,60%);"><strong>6006</strong></span><strong>. </strong>Wszystkie sprawy prowadzone pod tym JRWA są prowadzone elektronicznie (kolor zielony sprawy).</p><p>&nbsp;</p><p>❗❗ W przypadku lekarza należy sprawdzić czy ma uprawnienia do korzystanie z konta</p><h2><strong>Wpływ na email</strong></h2><p>Po wpłynięciu emaila zostaje on przekazany (przez wtyczkę w Outlook) przez jednego z pracowników do EZD na użytkownika "Aplikacje". Każdy w sekcji ma dostęp do tego użytkownika w trybie "w zastępstwie".</p><p><img src="https://knowly-strapi.ow03.nfz.gov.pl/uploads/zrzut_1_15988d2522.png" alt="zrzut_1.png">&nbsp;</p><p>Przechodzimy do tego użytkownika i przekazujemy koszulkę na swoje konto w EZD.&nbsp;</p><p>Otwieramy koszulkę i zakładamy nową sprawę pod JRWA<span style="color:hsl(0,75%,60%);"><strong> </strong></span><span style="color:hsl(120,75%,60%);"><strong>6006</strong></span><span style="color:hsl(60,75%,60%);"><strong>.</strong></span></p><p>Wypełniamy pole "nazwa" według wzorów poniżej:</p><pre><code class="language-plaintext">SZOI - Wniosek o nowe hasło - 3000</code></pre><pre><code class="language-plaintext">SNRL - Wniosek o nowe hasło - 3900</code></pre><p><span style="font-size:13px;"><i>np. SZOI - Wniosek o nowe hasło - 30000089, SNRL - Wniosek o nowe hasło - 39000001</i></span></p><p>&nbsp;</p><p>Uzupełniamy metadane pliku klikając na przycisk wskazany na zdjęciu poniżej</p><p><img src="https://knowly-strapi.ow03.nfz.gov.pl/uploads/zrzut_2_2e23f943cd.png" alt="zrzut_2.png"></p><p>&nbsp;</p><p>Jeżeli na wniosku widnieją podpisy osoby uprawnionej czyli:&nbsp;</p><ul><li>osoba której nazwisko widnieje w ks-sikch</li><li>osoba wskazana w KRS (dyrektor, jedna z osób w spółce)</li><li>kierownik apteki wskazany w ks-sikch</li><li>osoby która posiada pełnomocnictwo</li></ul><p>oraz widnieje pieczątka świadczeniodawcy lub lekarza, generujemy hasło i wysyłamy je w odpowiedzi na tego mejla.</p><p>&nbsp;</p><p>Na koniec dodajemy notatkę z informacją</p><pre><code class="language-plaintext">Nowe hasło wysłano na adres email dnia xx.xx.xxxx r.</code></pre><p>&nbsp;</p><h2><strong>Wpływ na kancelarię</strong></h2><p>Wniosek który wpłyną na kancelarię listownie lub osobiście jest rejestrowany i przekazywany do naczelnika wydziału.</p><p>Naczelnik przekazuje ( nie udostępnia! ) koszulkę danemu pracownikowi.</p><p>Po otrzymaniu takiej koszulki należy założyć sprawę oraz uzupełnić pole "nazwa" tak samo ja w przypadku wpływu na skrzynkę email.</p><p>Nowe hasło wysyłamy listownie na adres korespondencyjny. W ks-sikch szukamy lekarza lub świadczeniodawcy i przechodzimy do zakładki "adres korespondencyjny".&nbsp;</p><p>Po wysłaniu listu dodajemy notatkę</p><pre><code class="language-plaintext">Nowe hasło wysłano listownie na adres korespondencyjny dnia xx.xx.xxxx r.</code></pre><p>&nbsp;</p><p><span style="font-size:35px;">❗</span>Jeżeli na wniosku widnieje dopisany adres email nowe hasło wysyłamy meilowo, a w sprawie dodajemy notatkę</p><pre><code class="language-plaintext">Nowe hasło wysłano na adres email dnia xx.xx.xxxx r.</code></pre><p>&nbsp;</p><h2><strong>Wpływ osobiście</strong></h2><p>Może się zdarzyć, że lekarz lub świadczeniodawca przyjdzie do nas osobiście. W pierwszym kroku sprawdzamy czy osoba która przyszła ma prawo do otrzymania nowego hasła sprawdzając czy znajduje się w ks-sikch, KRS lub ma upoważnienie.&nbsp;</p><p>Jeżeli nie posiada wniosku o nowe hasło generujemy go pod adresem:</p><ul><li>dla świadczeniodawców<br><a href="https://www-2.nfz-lublin.pl/ap-mzwi-sso/servlet/mzwiregister/wizregstart">https://www-2.nfz-lublin.pl/ap-mzwi-sso/servlet/mzwiregister/wizregstart</a></li><li>dla lekarzy<br><a href="https://www-2.nfz-lublin.pl/ap-recepty/servlet/rec_chg_reg/wizregstart?typ=lek">https://www-2.nfz-lublin.pl/ap-recepty/servlet/rec_chg_reg/wizregstart?typ=lek</a></li></ul><p>Po podpisaniu wniosku (opcjonalnie pieczątka jeżeli posiada) generujemy i drukujemy nowe hasło. Po przekazaniu nowego hasła prosimy o podpis na dole wniosku z informacją o otrzymaniu hasła.</p><blockquote><p>Otrzymałem/łam dnia xx.xx.xxxx r. &lt;imię&gt;&lt;nazwisko&gt;</p></blockquote><p>Po wszystkim idziemy do kancelarii z wnioskiem i prosimy o przyjęcie go.</p><p>&nbsp;</p><p>Po jakimś czasie w ezd dostaniemy koszulkę z wnioskiem. Postępujemy z nią tak samo jak w przypadku wpływu na kancelarię czyli rejestrujemy pod JRWA <span style="color:hsl(120,75%,60%);"><strong>6006</strong></span><strong>,</strong><span style="color:hsl(120,75%,60%);"><strong> </strong></span>nadajemy nazwę oraz uzupełniamy metadane.</p><p>&nbsp;</p><p>Na koniec dodajemy notatkę o treści</p><pre><code class="language-plaintext">Nowe hasło odebrano osobiście dnia xx.xx.xxxx r.</code></pre><p>&nbsp;</p><h2><strong>Q&amp;A</strong></h2><p><strong>Co gdy wniosek podpisany jest elektronicznie?</strong></p><p>Sprawdzamy czy wniosek jest prawidłowo podpisany oraz czy podpisała go osoba uprawniona. Resztę wykonujemy jak w instukcji powyżej.</p>',
                            createdAt: '2023-03-09T09:30:16.450Z',
                            updatedAt: '2024-01-18T14:18:27.720Z',
                            publishedAt: '2023-11-23T12:56:25.472Z',
                            __contentType: 'api::page.page',
                            navigationItemId: 26,
                            createdBy: {},
                            updatedBy: {},
                            __templateName: 'Generic',
                        },
                        items: [],
                    },
                    {
                        id: 27,
                        title: 'Formularze rejestracyjne',
                        menuAttached: false,
                        order: 2,
                        path: '/baza-wiedzy/wi-sa/formularze-rejestracyjne',
                        type: 'WRAPPER',
                        uiRouterKey: 'formularze-rejestracyjne',
                        slug: 'baza-wiedzy-wi-sa-formularze-rejestracyjne',
                        external: false,
                        items: [
                            {
                                id: 28,
                                title: 'SZOI',
                                menuAttached: false,
                                order: 1,
                                path: '/baza-wiedzy/wi-sa/formularze-rejestracyjne/szoi',
                                type: 'INTERNAL',
                                uiRouterKey: 'szoi',
                                slug: 'baza-wiedzy-wi-sa-formularze-rejestracyjne-szoi',
                                external: false,
                                related: {
                                    id: 6,
                                    title: 'Formularze rejestracyjne SZOI ',
                                    content:
                                        '<p><img src="https://knowly-strapi.ow03.nfz.gov.pl/uploads/coming_soon_528962877b.png" alt="coming-soon.png"></p>',
                                    createdAt: '2023-03-09T10:20:47.452Z',
                                    updatedAt: '2024-01-18T14:17:40.635Z',
                                    publishedAt: '2023-03-09T10:21:29.377Z',
                                    __contentType: 'api::page.page',
                                    navigationItemId: 28,
                                    createdBy: {},
                                    updatedBy: {},
                                    __templateName: 'Generic',
                                },
                                items: [],
                            },
                            {
                                id: 29,
                                title: 'SIMP',
                                menuAttached: false,
                                order: 2,
                                path: '/baza-wiedzy/wi-sa/formularze-rejestracyjne/simp',
                                type: 'INTERNAL',
                                uiRouterKey: 'simp-1',
                                slug: 'baza-wiedzy-wi-sa-formularze-rejestracyjne-simp',
                                external: false,
                                related: {
                                    id: 7,
                                    title: 'Hasła SIMP',
                                    content:
                                        '<p><img src="https://knowly-strapi.ow03.nfz.gov.pl/uploads/coming_soon_528962877b.png" alt="coming-soon.png"></p>',
                                    createdAt: '2023-03-09T10:23:15.816Z',
                                    updatedAt: '2024-01-18T14:18:00.416Z',
                                    publishedAt: null,
                                    __contentType: 'api::page.page',
                                    navigationItemId: 29,
                                    createdBy: {},
                                    updatedBy: {},
                                    __templateName: 'Generic',
                                },
                                items: [],
                            },
                        ],
                    },
                    {
                        id: 30,
                        title: 'Uprawnienia',
                        menuAttached: false,
                        order: 3,
                        path: '/baza-wiedzy/wi-sa/uprawnienia',
                        type: 'WRAPPER',
                        uiRouterKey: 'uprawnienia',
                        slug: 'baza-wiedzy-wi-sa-uprawnienia',
                        external: false,
                        items: [
                            {
                                id: 32,
                                title: 'KS-SIKCH',
                                menuAttached: false,
                                order: 1,
                                path: '/baza-wiedzy/wi-sa/uprawnienia/kssikch',
                                type: 'INTERNAL',
                                uiRouterKey: 'ks-sikch',
                                slug: 'baza-wiedzy-wi-sa-uprawnienia-kssikch',
                                external: false,
                                related: {
                                    id: 8,
                                    title: 'Uprawnienia KS-SIKCH',
                                    content:
                                        '<p><img src="https://knowly_strapi.nfz-lublin.pl/uploads/coming_soon_3968c28fa6.png" alt="coming-soon.png"></p>',
                                    createdAt: '2023-03-09T10:24:05.517Z',
                                    updatedAt: '2024-01-18T13:36:43.107Z',
                                    publishedAt: '2023-03-09T10:24:07.262Z',
                                    __contentType: 'api::page.page',
                                    navigationItemId: 32,
                                    createdBy: {},
                                    updatedBy: {},
                                    __templateName: 'Generic',
                                },
                                items: [],
                            },
                            {
                                id: 31,
                                title: 'Kadry i płace',
                                menuAttached: false,
                                order: 2,
                                path: '/baza-wiedzy/wi-sa/uprawnienia/kadryiplace',
                                type: 'INTERNAL',
                                uiRouterKey: 'kadry-i-place',
                                slug: 'baza-wiedzy-wi-sa-uprawnienia-kadryiplace',
                                external: false,
                                related: {
                                    id: 3,
                                    title: 'Uprawnienia Kadry i Płace',
                                    content:
                                        '<p><img src="https://knowly_strapi.nfz-lublin.pl/uploads/coming_soon_3968c28fa6.png" alt="coming-soon.png"></p>',
                                    createdAt: '2023-03-09T09:40:43.008Z',
                                    updatedAt: '2024-01-18T13:36:42.713Z',
                                    publishedAt: '2023-03-09T10:04:40.038Z',
                                    __contentType: 'api::page.page',
                                    navigationItemId: 31,
                                    createdBy: {},
                                    updatedBy: {},
                                    __templateName: 'Generic',
                                },
                                items: [],
                            },
                        ],
                    },
                ],
            },
            {
                id: 33,
                title: 'WI-SEI',
                menuAttached: false,
                order: 2,
                path: '/baza-wiedzy/wi-sei',
                type: 'WRAPPER',
                uiRouterKey: 'wi-sei',
                slug: 'baza-wiedzy-wi-sei',
                external: false,
                items: [
                    {
                        id: 34,
                        title: 'Konta domenowe',
                        menuAttached: false,
                        order: 1,
                        path: '/baza-wiedzy/wi-sei/konta-domenowe',
                        type: 'INTERNAL',
                        uiRouterKey: 'konta-domenowe',
                        slug: 'baza-wiedzy-wi-sei-konta-domenowe',
                        external: false,
                        related: {
                            id: 10,
                            title: 'Konta domenowe',
                            content:
                                '<p><img src="https://knowly_strapi.nfz-lublin.pl/uploads/coming_soon_3968c28fa6.png" alt="coming-soon.png"></p>',
                            createdAt: '2023-03-09T10:27:51.557Z',
                            updatedAt: '2024-01-18T13:36:43.303Z',
                            publishedAt: '2023-03-09T10:27:53.221Z',
                            __contentType: 'api::page.page',
                            navigationItemId: 34,
                            createdBy: {},
                            updatedBy: {},
                            __templateName: 'Generic',
                        },
                        items: [],
                    },
                ],
            },
            {
                id: 35,
                title: 'WOKIP',
                menuAttached: false,
                order: 3,
                path: '/baza-wiedzy/wokip',
                type: 'WRAPPER',
                uiRouterKey: 'wokip',
                slug: 'baza-wiedzy-wokip',
                external: false,
                items: [],
            },
        ],
    },
    {
        id: 39,
        title: 'Adresy innych stron',
        menuAttached: false,
        order: 2,
        path: '/adresy-innych-stron',
        type: 'INTERNAL',
        uiRouterKey: 'adresy-innych-stron',
        slug: 'adresy-innych-stron-1',
        external: false,
        related: {
            id: 17,
            title: 'Adresy innych stron',
            content:
                '<p style="margin-left:0px;">EZD:</p><ul><li style="margin-left:0px;"><a href="http://ezd-instrukcja.nfz-lublin.pl/">Instrukcja EZD</a></li></ul><p style="margin-left:0px;">Księgowość:</p><ul><li><a href="http://10.40.1.5:9080/FKClassic7/entry">FK</a></li><li><a href="http://10.40.1.5:9080/PHW7_dk01">FK(nowa)</a></li></ul><p style="margin-left:0px;">WSOZ:</p><ul><li><a href="https://szoi2-c.nfz-lublin.pl/ap-jgp/">JPG</a></li><li><a href="https://dilo.nfz.gov.pl/ap-kolce/user/kolejkiwys/kolejkalst@default">KOLCE</a></li><li><a href="https://dilo.nfz.gov.pl/ap-dilo/">DiLO</a></li><li><a href="https://ewus.nfz.gov.pl/ap-ewus/">EWUŚ</a></li><li><a href="https://csm-swd.nfz.gov.pl/">SIMP dla świadczeniodawcy</a></li><li><a href="https://app.cen.nfz.gov.pl/csm-nfz/">SIMP</a></li><li><a href="http://kolejki.nfz.gov.pl/">kolejki – terminy leczenia</a></li><li><a href="https://uz.cen.nfz.gov.pl/ap-kosztlecz/user/mgr/welcome@default">koszty leczenia</a></li><li><a href="http://rejestr.nfz-lublin.pl/vpinfz">rejestr wniosków</a></li><li><a href="https://www-2.nfz-lublin.pl/ap-mzwi/">SZOI</a></li><li><a href="https://www-2.nfz-lublin.pl/ap-mzwi-adm/">SZOI administracyjny</a></li><li><a href="https://uz.cen.nfz.gov.pl/ap-zz-adm/admin/zzadm/wystzlectadmlst@default">Zaopatrzenie ortopedyczne SZOI</a></li></ul><p style="margin-left:0px;">kontrola:</p><ul><li><a href="https://szoi2-c.nfz-lublin.pl/ap-kontrole/">AP-kontrole</a></li><li><a href="https://poczta.nfz.gov.pl/">Dostęp do poczty służbowej przez Internet(dla uprawnionych)</a></li><li><a href="https://ssl.nfz-lublin.pl/vpn/">zdalny dostęp do zasobów wydziału kontroli oraz </a><a href="http://intranet.nfz-lublin.pl/obrazy/instrukcja_vpn.pdf">INSTRUKCJA</a></li><li><a href="https://ezd.cen.nfz.gov.pl/">EZD centrali</a></li></ul><p style="margin-left:0px;">uzdrowiska:</p><ul><li><a href="https://uz.cen.nfz.gov.pl/ap-uzdrow/">uzdrowiska</a></li><li><a href="https://skierowania.nfz.gov.pl/">wyszukiwarka skierowań sanatoryjnych</a></li></ul><p style="margin-left:0px;">WGL:</p><ul><li><a href="https://prod.ceidg.gov.pl/ceidg/ceidg.public.ui/search.aspx">CEIDG</a></li><li><a href="https://www-2.nfz-lublin.pl/ap-recepty/">SNRL</a></li><li><a href="https://www-2.nfz-lublin.pl/ap-recepty-adm/">SNRL administracyjny</a></li><li><a href="https://rpwdl.csioz.gov.pl/(X(1)S(hutilpsq35rwrg1pgah0qs2q))/RPZ/SearchEx?institutionType=L">RPWDL – rejestr praktyk zawodowych i podmiotów leczniczych</a></li><li><a href="http://stat.gov.pl/">GUS</a></li><li><a href="http://ra.rejestrymedyczne.csioz.gov.pl/_layouts/15/ra/glowna.aspx">rejestr aptek</a></li><li><a href="https://wyszukiwarkaregon.stat.gov.pl/appBIR/index.aspx">baza regon</a></li><li><a href="http://rejestr.nil.org.pl/xml/nil/rejlek/hurtd">Naczelna Izba Lekarska</a></li><li><a href="https://gabinet.gov.pl/">gabinet.gov.pl</a></li><li><a href="https://pacjent.gov.pl/">pacjent.gov.pl</a></li></ul><p style="margin-left:0px;">WFM:</p><ul><li><a href="https://sofu.cen.nfz.gov.pl/">SOFU</a></li><li><a href="http://10.10.38.52/cms/index.php?id=rina-home-page">wymiana formularzy w ramach UE</a></li><li><a href="https://ec.europa.eu/employment_social/social-security-directory/welcome.seam?langId=pl">Spis Europejskich Instytucji Zabezpieczenia Społecznego w ramach EESSI</a></li><li><a href="http://ecb.cen.nfz.gov.pl/KalkulatorECB.aspx">kalkulator walut</a></li></ul><p style="margin-left:0px;">WSS:</p><ul><li><a href="https://www.ekuz.nfz.gov.pl/">informacja EKUZ</a></li><li><a href="http://www.zus.pl/o-zus/kontakt/oddzialy-inspektoraty-biura-terenowe">ZUS</a></li><li><a href="https://zip.nfz.gov.pl/ap-portal/">ZIP</a></li><li><a href="https://adminzip.cen.nfz.gov.pl/ap-portal-adm/admin/pretend/oprlst@default">ZIP Administracja</a></li><li><a href="https://pz.gov.pl/">profil zaufany</a></li><li><a href="http://www.kpk.nfz.gov.pl/pl/16-pl/kpk/60-faq.html">Krajowy Punkt Kontaktowy</a></li><li><a href="https://dtransgraniczna.cen.nfz.gov.pl/ap-kpa/user/sprwkpa/wnkosztlst@default">dyrektywa transgraniczna – system obsługi spraw prowadzony zgodnie z kodeksem postępowania administracyjnego</a></li><li><a href="https://cwu.cen.nfz.gov.pl/">CWU</a></li><li><a href="http://10.10.34.52/">RINA</a></li><li><a href="http://www.nfz.gov.pl/">centrala</a></li><li><a href="http://www.cen.nfz.gov.pl/">intranet centrali</a></li><li><a href="http://www.mz.gov.pl/">MZ</a></li><li><a href="http://nfz-lublin.pl/%20target=">NFZ Lublin</a></li><li><a href="https://sip.legalis.pl/">LEX</a></li><li><a href="https://hr.nfz-lublin.pl/#!/login">portal pracowniczy</a></li><li><a href="https://sharepoint.cen.nfz.gov.pl/cen/dais/proj_nfz/_layouts/15/start.aspx#/Shared%20Documents/Forms/AllItems.aspx?RootFolder=%2Fcen%2Fdais%2Fproj%5Fnfz%2FShared%20Documents%2FProjekty%5F03OW&amp;FolderCTID=0x012000D61DCEB91C0B554D8E8309A877B8989C&amp;View=%7BDFD8591D%2D0C45%2D48A5%2D89B5%2DD2598683C6C6%7D">Projekty – sharepoint</a></li><li><a href="https://moj.gov.pl/uslugi/signer/upload?xFormsAppName=SIGNER">odczytanie pliku podpisanego w epuap</a></li><li><a href="https://aris.cen.nfz.gov.pl/">aris</a></li></ul><p style="margin-left:0px;">Inne:</p><ul><li><a href="http://kary.nfz-lublin.pl/">Portal kar</a></li><li><a href="https://baw.nfz.gov.pl/NFZ/tabBrowser/mainPage">Baza Aktów Własnych NFZ</a></li><li><a href="https://uz.cen.nfz.gov.pl/">Cenralny Moduł Administracji</a></li></ul>',
            createdAt: '2024-03-07T08:23:55.865Z',
            updatedAt: '2024-03-07T08:37:11.696Z',
            publishedAt: '2024-03-07T08:25:38.758Z',
            __contentType: 'api::page.page',
            navigationItemId: 39,
            createdBy: {},
            updatedBy: {},
            __templateName: 'Generic',
        },
        items: [],
    },
    {
        id: 38,
        title: 'Prasówka',
        menuAttached: false,
        order: 3,
        path: '/prasowka',
        type: 'INTERNAL',
        uiRouterKey: 'prasowka',
        slug: 'prasowka-1',
        external: false,
        related: {
            id: 16,
            title: 'Prasówka',
            content:
                '<p><img src="https://knowly-strapi.ow03.nfz.gov.pl/uploads/coming_soon_528962877b.png" alt="coming-soon.png"></p>',
            createdAt: '2024-03-07T08:14:44.817Z',
            updatedAt: '2024-03-08T09:47:59.983Z',
            publishedAt: '2024-03-07T08:14:48.511Z',
            __contentType: 'api::page.page',
            navigationItemId: 38,
            createdBy: {},
            updatedBy: {},
            __templateName: 'Generic',
        },
        items: [],
    },
    {
        id: 40,
        title: 'Strategia NFZ',
        menuAttached: false,
        order: 4,
        path: '/strategia-nfz',
        type: 'INTERNAL',
        uiRouterKey: 'strategia-nfz',
        slug: 'strategia-nfz-1',
        external: false,
        related: {
            id: 18,
            title: 'Strategia NFZ',
            content:
                '<h3>Strategia NFZ na lata 2019-2023</h3><ul><li><a href="https://knowly-strapi.ow03.nfz.gov.pl/uploads/uchwala7_2019iii_rady28_03_2019_6794a34f30.pdf">Uchwała nr 7_2019_III Rady NFZ z 28.03.2019 r.</a></li><li><a href="https://knowly-strapi.ow03.nfz.gov.pl/uploads/strategia2019_23_a1dd7a92e5.pdf">Strategia NFZ na lata 2019 - 2023</a></li><li><a href="https://knowly-strapi.ow03.nfz.gov.pl/uploads/mapacelow2019_2023_5ccb7f7824.pdf">Mapa celów 2019 - 2023</a></li></ul><p>Misja i wizja:</p><p><img src="https://knowly-strapi.ow03.nfz.gov.pl/uploads/misjawizja_a151328c38.jpg" alt="misjawizja.jpg"></p><p>Kluczowe wartości strategii NFZ:</p><p><img src="https://knowly-strapi.ow03.nfz.gov.pl/uploads/wartoscinfz_1546c1b4b4.png" alt="wartoscinfz.png"></p>',
            createdAt: '2024-03-07T08:39:56.500Z',
            updatedAt: '2024-03-08T08:49:59.457Z',
            publishedAt: '2024-03-08T08:49:59.446Z',
            __contentType: 'api::page.page',
            navigationItemId: 40,
            createdBy: {},
            updatedBy: {},
            __templateName: 'Generic',
        },
        items: [],
    },
    {
        id: 41,
        title: 'Raporty',
        menuAttached: false,
        order: 5,
        path: '/raporty',
        type: 'WRAPPER',
        uiRouterKey: 'raporty',
        slug: 'raporty-1',
        external: false,
        items: [
            {
                id: 42,
                title: 'Projekty',
                menuAttached: false,
                order: 1,
                path: '/raporty/projekty',
                type: 'INTERNAL',
                uiRouterKey: 'projekty',
                slug: 'raporty-projekty',
                external: false,
                related: {
                    id: 19,
                    title: 'Projekty',
                    content:
                        '<h3 style="margin-left:0px;">Projekty OW NFZ 2024 r.</h3><ul><li><a href="https://knowly-strapi.ow03.nfz.gov.pl/uploads/Portfel_Projektow_na_2024_r_Lubelskiego_Oddzialu_Funduszu_c322c47fef.pdf">Portfel projektów lubelskiego OW NFZ 2024 r. (pdf)</a></li><li><a href="https://knowly-strapi.ow03.nfz.gov.pl/uploads/03_OW_Ewidencja_Projektow2024_rejestr_projektow_09f483b3b9.xlsx">Rejestr projektów lubelskiego OW NFZ 2024 r. (xls)</a></li></ul><h3 style="margin-left:0px;">Projekty OW NFZ 2023 r.</h3><ul><li><a href="https://knowly-strapi.ow03.nfz.gov.pl/uploads/portfelprojektow2023_81128acb52.pdf">Portfel projektów lubelskiego OW NFZ 2023 r. (pdf)</a></li><li><a href="https://knowly-strapi.ow03.nfz.gov.pl/uploads/I_kw_2023_r_Sprawozdanie_z_Portfela_Projektow_Lubelskiego_Oddzialu_Funduszu_2023_4c79c112d3.pdf">Sprawozdanie z portfela projektów lubelskiego oddziału funduszu za I kwartał 2023 r. (pdf)</a></li><li><a href="https://knowly-strapi.ow03.nfz.gov.pl/uploads/II_kw_2023_r_Sprawozdanie_z_Portfela_Projektow_Lubelskiego_Oddzialu_Funduszu_2023_72b2619a3b.pdf">Sprawozdanie z portfela projektów lubelskiego oddziału funduszu za II kwartał 2023 r. (pdf)</a></li><li><a href="https://knowly-strapi.ow03.nfz.gov.pl/uploads/III_kw_2023_r_Sprawozdanie_z_Portfela_Projektow_Lubelskiego_Oddzialu_Funduszu_2023_3e14cea86e.pdf">Sprawozdanie z portfela projektów lubelskiego oddziału funduszu za III kwartał 2023 r. (pdf)</a></li><li><a href="https://knowly-strapi.ow03.nfz.gov.pl/uploads/IV_kw_2023_r_Sprawozdanie_z_Portfela_Projektow_Lubelskiego_Oddzialu_Funduszu_2023_6b6b392909.pdf">Sprawozdanie z portfela projektów lubelskiego oddziału funduszu za IV kwartał 2023 r. (pdf)</a></li><li><a href="https://knowly-strapi.ow03.nfz.gov.pl/uploads/03_OW_Ewidencja_Projektow2023_rejestr_projektow_954165eac8.xlsx">Rejestr projektów lubelskiego OW NFZ 2023 r. (xls)</a></li></ul><h3>Projekty OW NFZ 2022 r.</h3><ul><li><a href="https://knowly-strapi.ow03.nfz.gov.pl/uploads/IV_kw_2022_r_Sprawozdanie_z_Portfela_Projektow_Lubelskiego_Oddzialu_Funduszu_2022_d4161729df.pdf">Sprawozdanie z realizacji portfela projektów lubelskiego OW za IV kwartał 2022 r.</a></li><li><a href="https://knowly-strapi.ow03.nfz.gov.pl/uploads/Portfel_Projektow_2022_r_stan_na_31_12_2022_r_d3b11d05b2.pdf">Portfel projektów lubelskiego OW NFZ stan na 31 grudnia 2022 r.</a></li><li><a href="https://knowly-strapi.ow03.nfz.gov.pl/uploads/sprrealizacji_Portfela_III_kw_2022_1191e99ae5.pdf">Sprawozdanie z realizacji portfela projektów lubelskiego OW NFZ za III kwartał 2022 r.</a></li><li><a href="https://knowly-strapi.ow03.nfz.gov.pl/uploads/portfelprojektow2022_stan_na_30_09_2022_995620da12.pdf">Portfel projektów lubelskiego OW NFZ stan na 30 września 2022 r.</a></li><li><a href="https://knowly-strapi.ow03.nfz.gov.pl/uploads/sprrealizacji_Portfela_II_kw_2022_e63d2c76b2.pdf">Sprawozdanie z realizacji portfela projektów lubelskiego OW NFZ za II kwartał 2022 r.</a></li><li><a href="https://knowly-strapi.ow03.nfz.gov.pl/uploads/Raport_Stanu_Portfela_Projektow_LOWNFZ_Ikw2022_0081ce206b.pdf">Raport I kwartał 2022 r.</a></li><li><a href="https://knowly-strapi.ow03.nfz.gov.pl/uploads/03_OW_Ewidencja_Projektow2022_4e9171f989.xlsx">Ewidencja projektów 2022 r.</a></li><li><a href="https://knowly-strapi.ow03.nfz.gov.pl/uploads/plan_Proj2022_9b6e2fb84a.xlsx">Plan projektów do realizacji w 2022 r.</a></li></ul><h3 style="margin-left:0px;">Projekty OW NFZ 2021 r.</h3><ul><li><a href="https://knowly-strapi.ow03.nfz.gov.pl/uploads/sprrealizacji_Portfela_I1_9_2021_386075b700.pdf">Sprawozdanie z realizacji portfela projektów lubelskiego OW NFZ w miesiącach I-IX 2021 r.</a></li><li><a href="https://knowly-strapi.ow03.nfz.gov.pl/uploads/sprrealizacji_Portfela_I2021_d7adc5ac32.pdf">Sprawozdanie z realizacji portfela projektów lubelskiego OW NFZ za 2021 r.</a></li><li><a href="https://knowly-strapi.ow03.nfz.gov.pl/uploads/03_OW_Ewidencja_Projektow2021_0cd0065006.xlsx">Ewidencja projektów 2021 r.</a></li><li><a href="https://sharepoint.cen.nfz.gov.pl/cen/dais/proj_nfz/_layouts/15/WopiFrame2.aspx?sourcedoc=%7BD1F0C686-A0EF-4E16-8E72-1A9F80C77D92%7D&amp;file=Raport%20stanu%20portfela%20projekt%C3%B3w%20w%20Lubelskim%20OW%20w%20I%20kwartale%202021%20r.pdf&amp;action=default">Raport I kwartał 2021 r.</a></li><li><a href="https://sharepoint.cen.nfz.gov.pl/cen/dais/proj_nfz/_layouts/15/WopiFrame.aspx?sourcedoc=%7B737A901A-B127-432B-BCC6-9D56907C1C59%7D&amp;file=Raport%20stanu%20portfela%20projekt%C3%B3w%20w%20Lubelskim%20OW%20NFZ%20w%20II%20kwartale%202021%20r.pdf&amp;action=default">Raport II kwartał 2021 r.</a></li><li><a href="https://knowly-strapi.ow03.nfz.gov.pl/uploads/Raport_Stanu_Portfela_Projektow_LOWNFZ_II_Ikw2021_d9c658ce23.pdf">Raport III kwartał 2021 r.</a></li><li><a href="https://knowly-strapi.ow03.nfz.gov.pl/uploads/Raport_Stanu_Portfela_Projektow_LOWNFZ_ivkw2021_f072f3591a.pdf">Raport IV kwartał 2021 r.</a></li></ul><h3 style="margin-left:0px;">Przedsięwzięcia Oddziału wspierające realizację Strategii Narodowego Funduszu Zdrowia w roku 2021</h3><ul><li><a href="https://knowly-strapi.ow03.nfz.gov.pl/uploads/projektyprzedsiewziecia2021_580de4ddae.xlsx">Projekty i przedsięwzięcia strategiczne realizowane w 2021 r. w lubelskim oddziale wojewódzki NFZ</a></li><li><a href="https://knowly-strapi.ow03.nfz.gov.pl/uploads/portfelprojektow_2019_2022_0bf27b7e6e.xlsx">Portfel projektów lubelskiego OW NFZ 2019-2022</a></li></ul><h3 style="margin-left:0px;">Projekty OW NFZ 2020 r.</h3><ul><li><a href="https://sharepoint.cen.nfz.gov.pl/cen/dais/proj_nfz/_layouts/15/WopiFrame2.aspx?sourcedoc=%7BCE90E484-2729-4260-9135-401203561A1D%7D&amp;file=03_OW_Ewidencja%20projekt%C3%B3w_2020.xlsx&amp;action=default&amp;CT=1627474075413&amp;OR=DocLibClassicUI">Ewidencja projektów 2020 r.</a></li><li><a href="https://sharepoint.cen.nfz.gov.pl/cen/dais/proj_nfz/_layouts/15/WopiFrame2.aspx?sourcedoc=%7B410B208E-9968-43E3-8FF4-54FA5A7F0064%7D&amp;file=03_OW_Raporty%20zbiorcze%20projekt%C3%B3w%202020.xlsx&amp;action=default&amp;CT=1627474127468&amp;OR=DocLibClassicUI">Raport zbiorczy za 2020 r.</a></li></ul><h3 style="margin-left:0px;">Projekty OW NFZ 2019 r.</h3><ul><li><a href="https://knowly-strapi.ow03.nfz.gov.pl/uploads/03_OW_Ewidencja_Projektow2019_bc195a676b.xlsx">Ewidencja raportów 2019 r.</a></li><li><a href="https://sharepoint.cen.nfz.gov.pl/cen/dais/proj_nfz/_layouts/15/WopiFrame2.aspx?sourcedoc=%7B448A3187-531A-4667-AD95-2678FED001B6%7D&amp;file=03_OW_Raporty%20zbiorcze%20projekt%C3%B3w%202019.xlsx&amp;action=default&amp;CT=1627474094261&amp;OR=DocLibClassicUI">Raport zbiorczy za 2019 r.</a></li></ul><hr><ul><li><a href="https://knowly-strapi.ow03.nfz.gov.pl/uploads/Metodyka_zarzadzania_portfelem_projektow_wersja_2_0_a8a439b574.pdf">Metodyka zarządzania projektami w NFZ wersja 2.0</a></li></ul><h4>Procedury</h4><ul><li><a href="https://knowly-strapi.ow03.nfz.gov.pl/uploads/Procedura_Zarzadzanie_projektami_v_2_1_5a087f5f22.pdf">Procedura zarządzania projektami</a></li><li><a href="https://knowly-strapi.ow03.nfz.gov.pl/uploads/Zal_nr_1_Karta_projektu_7b7e8f3913.xlsm">Załącznik nr 1 - karta projektu</a></li><li><a href="https://knowly-strapi.ow03.nfz.gov.pl/uploads/Zal_nr_2_Raport_koncowy_874972d5aa.docx">Załącznik nr 2 - raport końcowy</a></li><li><a href="https://knowly-strapi.ow03.nfz.gov.pl/uploads/Zal_nr_3_Struktura_projektowa_d4dff2f612.docx">Załącznik nr 3 - struktura projektowa</a></li><li><a href="https://knowly-strapi.ow03.nfz.gov.pl/uploads/Zal_nr_4_Wniosek_o_zgode_na_wstrzymanie_projektu_84eabb62b9.docx">Załącznik nr 4 - wniosek o zgodę na wstrzymanie projektu</a></li><li><a href="https://knowly-strapi.ow03.nfz.gov.pl/uploads/Zal_nr_5_Wniosek_o_zgode_na_wczesniejsze_zamkniecie_projektu_6fb1022cd3.docx">Załącznik nr 5 - wniosek o zgodę na wcześniejsze zamknięcie projektu</a></li><li><a href="https://knowly-strapi.ow03.nfz.gov.pl/uploads/Zal_nr_6_Wniosek_o_zgode_na_wprowadzenie_zmian_w_projekcie_265d02d93a.docx">Załącznik nr 6 - wniosek o zgodę na wprowadzenie zmian w projekcie</a></li><li><a href="https://knowly-strapi.ow03.nfz.gov.pl/uploads/Zal_nr_7_Indywidualny_Plan_Zatrudniania_80584eb89c.docx">Załącznik nr 7 - indywidualny plan zatrudniania</a></li><li><a href="https://knowly-strapi.ow03.nfz.gov.pl/uploads/Zal_nr_8_Wniosek_o_zgode_na_przygotowanie_projektu_finansowanego_ze_zrodel_zewnetrznych_bca8c44e7a.docx">Załącznik nr 8 - wniosek o zgodę a przygotowanie projektu finansowanego ze źródeł zewnętrznych</a></li><li><a href="https://knowly-strapi.ow03.nfz.gov.pl/uploads/Zal_nr_9_Zbiorczy_Plan_Zatrudniania_9a97a2ff9f.docx">Załącznik nr 9 - zbiorczy plan zatrudniania</a></li><li><a href="https://knowly-strapi.ow03.nfz.gov.pl/uploads/Zal_nr_10_Miesieczna_karta_realizacji_zadan_bd2190dced.docx">Załącznik nr 10 - miesięczna karta realizacji zadań</a></li></ul><p>&nbsp;</p><ul><li><a href="https://www.cen.nfz.gov.pl/index.php?option=com_content&amp;view=article&amp;id=4283:materiay-szkoleniowe-hadrone-ppm&amp;catid=114:zarzadzanie-projektami&amp;Itemid=138">Szkolenie hadrone</a></li><li><a href="https://knowly-strapi.ow03.nfz.gov.pl/uploads/sptk_BP_Pi_Lier_Projt20_01_2022_c0f2c17890.pdf">Prezentacja dotycząca zarządzania projektami - materiał opracowany przez wydział zarządzania projektami gabinetu prezesa funduszu</a></li><li><a href="https://knowly-strapi.ow03.nfz.gov.pl/uploads/Spotkanie_Biura_Portfela_15_03_2023_2ef06b7970.pdf">Prezentacja dotycząca zarządzania projektami - spotkanie biura portfela projektów 15 marca 2023 r.</a></li></ul><p>&nbsp;</p><ul><li><a href="https://knowly-strapi.ow03.nfz.gov.pl/uploads/zarz_ryzykiem_w_proj_realizowanych_w_NFZ_0d40d4cbf9.docx">Zarządzanie ryzykiem w projektach realizowanych w Narodowym Funduszu Zdrowia</a></li><li><a href="https://knowly-strapi.ow03.nfz.gov.pl/uploads/ryzyk_proj_6584c7e329.xlsx">Katalog ryzyk projektowych</a></li></ul>',
                    createdAt: '2024-03-08T08:52:27.708Z',
                    updatedAt: '2024-03-08T12:01:20.686Z',
                    publishedAt: '2024-03-08T12:01:20.675Z',
                    __contentType: 'api::page.page',
                    navigationItemId: 42,
                    createdBy: {},
                    updatedBy: {},
                    __templateName: 'Generic',
                },
                items: [],
            },
            {
                id: 43,
                title: 'Sprawozdania',
                menuAttached: false,
                order: 2,
                path: '/raporty/sprawozdania',
                type: 'INTERNAL',
                uiRouterKey: 'sprawozdania-1',
                slug: 'raporty-sprawozdania',
                external: false,
                related: {
                    id: 20,
                    title: 'Sprawozdania',
                    content:
                        '<h2>I. Działalność Oddziału</h2><h4>Rok 2023</h4><ul><li><a href="https://knowly-strapi.ow03.nfz.gov.pl/uploads/sprawozdanie_z_dzialalnosci_Oddzialu_za_I_kwartal_2023_f4e9108816.pdf">Sprawozdanie za I kwartał 2023 r.</a></li><li><a href="https://knowly-strapi.ow03.nfz.gov.pl/uploads/sprawozdanie_z_dzialalnosci_Oddzialu_za_II_kwartal_2023_0200d94934.pdf">Sprawozdanie za II kwartał 2023 r.</a></li><li><a href="https://knowly-strapi.ow03.nfz.gov.pl/uploads/sprawozdanie_z_dzialalnosci_Oddzialu_za_III_kwartal_2023_99cd52243b.pdf">Sprawozdanie za III kwartał 2023 r.</a></li></ul><h4>Rok 2022</h4><ul><li><a href="https://knowly-strapi.ow03.nfz.gov.pl/uploads/Spr_Dzialalnosci_Pierwszy_Kw2022_e01728fd15.pdf">Sprawozdanie za I kwartał 2022 r.</a></li><li><a href="https://knowly-strapi.ow03.nfz.gov.pl/uploads/Spr_Dzialalnosci_Drugi_Kw2022_bd24e7af9c.pdf">Sprawozdanie za II kwartał 2022 r.</a></li><li><a href="https://knowly-strapi.ow03.nfz.gov.pl/uploads/Sprawozdanie_z_dzialalnosci_III_kw_2022_e7461c6fec.pdf">Sprawozdanie za III kwartał 2022 r.</a></li><li><a href="https://knowly-strapi.ow03.nfz.gov.pl/uploads/sprawozdanie_z_dzialalnosci_Oddzialu_za_IV_kwartal_2022_ce77c81201.pdf">Sprawozdanie za IV kwartał 2022 r.</a></li><li><a href="https://knowly-strapi.ow03.nfz.gov.pl/uploads/Sprawozdanie_z_dzialalnosci_oddzialu_w_2022_roku_6dbc9cecee.pdf">Sprawozdanie z działalności oddziału w 2022 r.</a></li></ul><h4>Rok 2021</h4><ul><li><a href="https://knowly-strapi.ow03.nfz.gov.pl/uploads/Spr_Dzialalnosci_Pierwszy_Kw2021_686ffda08b.pdf">Sprawozdanie za I kwartał 2021 r.</a></li><li><a href="https://knowly-strapi.ow03.nfz.gov.pl/uploads/Spr_Dzialalnosci_Drugi_Kw2021_ca2ffb7ac7.pdf">Sprawozdanie za II kwartał 2021 r.</a></li><li><a href="https://knowly-strapi.ow03.nfz.gov.pl/uploads/Spr_Dzialalnosci_Trzeci_Kw2021_78aaea721b.pdf">Sprawozdanie za III kwartał 2021 r.</a></li><li><a href="https://knowly-strapi.ow03.nfz.gov.pl/uploads/Spr_Dzialalnosci_Czwarty_Kw2021_0f916ad276.pdf">Sprawozdanie za IV kwartał 2021 r.</a></li><li><a href="https://knowly-strapi.ow03.nfz.gov.pl/uploads/Spr_Dzialalnosci2021_7216ac8270.pdf">Sprawozdanie za 2021 r.</a></li></ul><h2>II. Plan pracy oddziału</h2><h4>Rok 2023</h4><ul><li><a href="https://knowly-strapi.ow03.nfz.gov.pl/uploads/Plan_pracy_Lubelskiego_Oddzialu_Wojewodzkiego_na_2023_rok_493877a5f9.pdf">Plan pracy lubelskiego OW NFZ na 2023 r.</a></li><li><a href="https://knowly-strapi.ow03.nfz.gov.pl/uploads/sprawozdanie_z_realizacji_planu_pracy_za_I_kw_2023_64b0a7268a.pdf">Sprawozdanie z realizacji planu pracy za I kwartał 2023 r.</a></li><li><a href="https://knowly-strapi.ow03.nfz.gov.pl/uploads/sprawozdanie_z_realizacji_Planu_pracy_na_koniec_II_kwartalu_2023_495ba15ed6.pdf">Sprawozdanie z realizacji planu pracy za II kwartał 2023 r.</a></li><li><a href="https://knowly-strapi.ow03.nfz.gov.pl/uploads/sprawozdanie_z_realizacji_Planu_pracy_na_koniec_III_kwartalu_2023_f727beb5d7.pdf">Sprawozdanie z realizacji planu pracy za III kwartał 2023 r.</a></li><li><a href="https://knowly-strapi.ow03.nfz.gov.pl/uploads/sprawozdanie_z_realizacji_Planu_pracy_na_koniec_IV_kwartalu_2023_5f3609bc0e.pdf">Sprawozdanie z realizacji planu pracy za IV kwartał 2023 r.</a></li></ul><h4>Rok 2022</h4><ul><li><a href="https://knowly-strapi.ow03.nfz.gov.pl/uploads/Plan_Pracy_LOWNFZ_2022_6d5c15d4c3.pdf">Plan pracy lubelskiego OW NFZ na 2022 r.</a></li><li><a href="https://knowly-strapi.ow03.nfz.gov.pl/uploads/Realizacja_Planu_Pracy_LOWNFZ_I_kw_2022_17d7b02aa8.pdf">Sprawozdanie z realizacji planu pracy za I kwartał 2022 r.</a></li><li><a href="https://knowly-strapi.ow03.nfz.gov.pl/uploads/sprawozdanie_z_realizacji_planu_pracy_za_II_kwartal_2022_r_cdccb265f5.pdf">Sprawozdanie z realizacji planu pracy za II kwartał 2022 r.</a></li><li><a href="https://knowly-strapi.ow03.nfz.gov.pl/uploads/SPRAWOZDANIE_Z_REALIZACJI_PLANU_PRACY_NA_KONIEC_III_KWARTALU_2022_ROKU_52e1e97e4b.pdf">Sprawozdanie z realizacji planu pracy za III kwartał 2022 r.</a></li><li><a href="https://knowly-strapi.ow03.nfz.gov.pl/uploads/sprawozdanie_z_realizacji_Planu_pracy_na_koniec_IV_kw_2022_r_f040f7b957.pdf">Sprawozdanie z realizacji planu pracy za IV kwartał 2022 r.</a></li></ul><h4>Rok 2021</h4><ul><li><a href="https://knowly-strapi.ow03.nfz.gov.pl/uploads/Plan_Pracy_LOWNFZ_2021_2033bf9f81.pdf">Plan pracy lubelskiego OW NFZ na 2021 r.</a></li><li><a href="https://knowly-strapi.ow03.nfz.gov.pl/uploads/Realizacja_Planu_Pracy_LOWNFZ_I_kw_2021_6329278220.pdf">Sprawozdanie z realizacji planu pracy za I kwartał 2021 r.</a></li><li><a href="https://knowly-strapi.ow03.nfz.gov.pl/uploads/Realizacja_Planu_Pracy_LOWNFZ_II_kw_2021_f36b0d85da.pdf">Sprawozdanie z realizacji planu pracy za II kwartał 2021 r.</a></li><li><a href="https://knowly-strapi.ow03.nfz.gov.pl/uploads/Realizacja_Planu_Pracy_LOWNFZ_III_kw_2021_3dc2843c20.pdf">Sprawozdanie z realizacji planu pracy za III kwartał 2021 r.</a></li><li><a href="https://knowly-strapi.ow03.nfz.gov.pl/uploads/Realizacja_Planu_Pracy_LOWNFZ_IV_kw_2021_b66c63d7ed.pdf">Sprawozdanie z realizacji planu pracy za IV kwartał 2021 r.</a></li></ul>',
                    createdAt: '2024-03-08T10:36:19.574Z',
                    updatedAt: '2024-03-08T12:01:24.888Z',
                    publishedAt: '2024-03-08T12:01:24.877Z',
                    __contentType: 'api::page.page',
                    navigationItemId: 43,
                    createdBy: {},
                    updatedBy: {},
                    __templateName: 'Generic',
                },
                items: [],
            },
            {
                id: 44,
                title: 'Kontrola zarządcza',
                menuAttached: false,
                order: 3,
                path: '/raporty/kontrola-zarzadcza',
                type: 'INTERNAL',
                uiRouterKey: 'kontrola-zarzadcza',
                slug: 'raporty-kontrola-zarzadcza',
                external: false,
                related: {
                    id: 21,
                    title: 'Kontrola zarządzcza',
                    content:
                        '<h4>2023</h4><ul><li><a href="https://knowly-strapi.ow03.nfz.gov.pl/uploads/Raport_z_Samooceny_kontroli_zarzadczej_za_2023_r_Lubelski_Oddzial_Funduszu_88b0576091.pdf">Raport samooceny kontroli zarządczej za 2023 r. Lubelski Oddział Funduszu</a></li></ul><h4>2022</h4><ul><li><a href="https://knowly-strapi.ow03.nfz.gov.pl/uploads/Raport_z_Samooceny_kontroli_zarzadczej_za_2022_r_Lubelski_Oddzial_Funduszu_d5ad415bb8.pdf">Raport samooceny kontroli zarządczej za 2022 r. Lubelski Oddział Funduszu</a></li><li><a href="https://knowly-strapi.ow03.nfz.gov.pl/uploads/Lubelski_OW_Katalog_ryzyk_2022_f2049b5ff8.xlsx">Lubelski OW katalog ryzyk 2022 r.</a></li><li><a href="https://knowly-strapi.ow03.nfz.gov.pl/uploads/Lubelski_OW_Zalacznik_do_katalogu_oceny_ryzyka_cf287cf452.xlsx">Lubelski OW załącznik do katalogu oceny ryzyka</a></li></ul><h4>2021</h4><ul><li><a href="https://knowly-strapi.ow03.nfz.gov.pl/uploads/Raport_Samooceny_Kontr_Zarz_b08a576777.pdf">Raport z oceny ryzyka przeprowadzonej w 2021 r. w lubelskim OW NFZ</a></li><li><a href="https://knowly-strapi.ow03.nfz.gov.pl/uploads/raport_analizaryzyk_29047a67c8.pdf">Raport - analiza ryzyk</a></li><li><a href="https://knowly-strapi.ow03.nfz.gov.pl/uploads/katalog_ryzyk_4ffeb177e9.xlsx">Lubelski oddział katalog ryzyk</a></li><li><a href="https://knowly-strapi.ow03.nfz.gov.pl/uploads/zal_katlalogryzyk_e97f2bf0e5.xlsx">Lubelski oddział załącznik do katalogu ryzyk</a></li><li><a href="https://knowly-strapi.ow03.nfz.gov.pl/uploads/stan_Kontroli_Zarz_e098daf251.pdf">Poprawa stanu kontroli zarządczej i półrocze 2021 r.</a></li></ul><h4>2020</h4><ul><li><a href="https://knowly-strapi.ow03.nfz.gov.pl/uploads/Raport_Samooceny_Kontr_Zarz_b08a576777.pdf">Raport z samooceny kontroli zarządczej lubelskiego OW NFZ za 2020 r.</a></li></ul>',
                    createdAt: '2024-03-08T12:39:33.538Z',
                    updatedAt: '2024-03-08T12:53:08.845Z',
                    publishedAt: '2024-03-08T12:53:08.833Z',
                    __contentType: 'api::page.page',
                    navigationItemId: 44,
                    createdBy: {},
                    updatedBy: {},
                    __templateName: 'Generic',
                },
                items: [],
            },
            {
                id: 45,
                title: 'Petycje',
                menuAttached: false,
                order: 4,
                path: '/raporty/petycje',
                type: 'INTERNAL',
                uiRouterKey: 'petycje',
                slug: 'raporty-petycje',
                external: false,
                related: {
                    id: 22,
                    title: 'Petycje',
                    content:
                        '<ul><li><a href="https://knowly-strapi.ow03.nfz.gov.pl/uploads/Informacja_o_petycjach_za_2022_rok_d5ccd9a7d7.docx">Petycje złożone w Lubelskim OW NFZ w 2022 r.</a></li><li><a href="https://knowly-strapi.ow03.nfz.gov.pl/uploads/petycje2021_e09c64bfd8.pdf">Petycje złożone w Lubelskim OW NFZ w 2021 r.</a></li></ul>',
                    createdAt: '2024-03-08T12:56:58.250Z',
                    updatedAt: '2024-03-08T12:58:32.002Z',
                    publishedAt: '2024-03-08T12:58:31.993Z',
                    __contentType: 'api::page.page',
                    navigationItemId: 45,
                    createdBy: {},
                    updatedBy: {},
                    __templateName: 'Generic',
                },
                items: [],
            },
        ],
    },
]
