export const MenuItems = () => {
  return (
    <div>
      <ul>
        <li>el</li>
        <li>el</li>
        <li>el</li>
        <li>el</li>
        <li>el</li>
        <li>el</li>
        <li>el</li>
        <li>el</li>
        <li>el</li>
        <li>el</li>
        <li>el</li>
        <li>el</li>
        <li>el</li>
        <li>el</li>
        <li>el</li>
        <li>el</li>
        <li>el</li>
        <li>el</li>
        <li>el</li>
        <li>el</li>
        <li>el</li>
        <li>el</li>
        <li>el</li>
        <li>el</li>
        <li>el</li>
        <li>el</li>
        <li>el</li>
        <li>el</li>
        <li>el</li>
        <li>el</li>
        <li>el</li>
        <li>el</li>
        <li>el</li>
        <li>el</li>
        <li>el</li>
        <li>el</li>
        <li>el</li>
        <li>el</li>
        <li>el</li>
        <li>el</li>
        <li>el</li>
        <li>el</li>
        <li>el</li>
        <li>el</li>
        <li>el</li>
        <li>el</li>
        <li>el</li>
        <li>el</li>
      </ul>
    </div>
  );
};
